### ISSUE TITLE
Add test cases for Armenian GPOS/GSUB?

### ISSUE THREAD

**Issue by brawer** [notofonts/armenian#1]
@marekjez86, in https://github.com/googlei18n/noto-fonts/pull/862#issuecomment-284557864 there was a concern that Noto Armenian may need contextual glyph substitution and positioning. Mind following up on this, and adding test cases to https://github.com/googlei18n/noto-source/tree/master/test/Armenian if needed?

**Comment by simoncozens** [comment]
There's been no follow up on this, and I suspect that the initial concerns are lost to the midst of time. If any Armenian users are seeing problems, I trust they'll tell us about them...
