### ISSUE TITLE
Was Noto Sans Armenian removed / not on GitHub Pages?

### ISSUE THREAD

**Issue by mapmeld** [notofonts/armenian#11]
## Defect Report

I'm working on a script to download the latest build of fonts from Noto repos.

The Noto Sans Armenian section and NotoSansArmenian-Regular.ttf download previously appeared on https://notofonts.github.io/armenian/ but are no longer available

If this is a more permanent change, I'm happy to use the Serif version, but please make a note.
Otherwise it may be fixed by rebuilding the page

The jsdelivr CDN isn't reliable for larger fonts (Bengali UI), so typically I use the GitHub Pages branch of Noto repos.

Edit: see [GitHub Actions output here](https://github.com/notofonts/armenian/actions/runs/7556307340/job/20573036037#step:7:16)
```
(for config in sources/config*.yaml; do . venv/bin/activate; python3 -m notobuilder $config; done)  && touch build.stamp
[1/311] instantiateUfo
fontmake -i Noto Sans Armenian Regular -o ufo -m NotoSansArmenian.designspace --ufo-structure=json --output-dir instance_ufos
[2/311] instantiateUfo
fontmake -i Noto Sans Armenian Light -o ufo -m NotoSansArmenian.designspace --ufo-structure=json --output-dir instance_ufos
[3/311] instantiateUfo
fontmake -i Noto Sans Armenian ExtraLight -o ufo -m NotoSansArmenian.designspace --ufo-structure=json --output-dir instance_ufos
[4/311] instantiateUfo
fontmake -i Noto Sans Armenian Thin -o ufo -m NotoSansArmenian.designspace --ufo-structure=json --output-dir instance_ufos
[5/311] buildVariable
FAILED: /tmp/tmpx05bjv8f 
/home/runner/work/armenian/armenian/venv/bin/python3 -m gftools.builder.jobrunner fontmake --output-path /tmp/tmpx05bjv8f -o variable -m NotoSansArmenian.designspace --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter 

Command failed:
fontmake --output-path /tmp/tmpx05bjv8f -o variable -m NotoSansArmenian.designspace --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
```

**Comment by simoncozens** [comment]
Yep, looks like I've broken the build when I removed the semibold master. I'll fix it. By the way, the fonts on `https://notofonts.github.io/<script>` are development (CI) builds. For latest releases, you want https://notofonts.github.io/#armenian

**Comment by simoncozens** [comment]
It's back again now!
