### ISSUE TITLE
Full now has mismatched Latin weights

### ISSUE THREAD

**Issue by DLasher106** [notofonts/armenian#12]
In the latest full version development builds from https://notofonts.github.io/armenian/ the weight of the Latin letters has become mismatched (too heavy).

![Untitled](https://github.com/notofonts/armenian/assets/18547206/2e4ba4da-af09-484d-900c-9a9cdf99cd30)

This seems to have occurred after the Oct 16, 2023 build.

**Comment by simoncozens** [comment]
Thanks, I understand why this is happening; it's a bug in our merger, which does not handle sparse masters correctly.

**Comment by simoncozens** [comment]
This should now be fixed.
