### ISSUE TITLE
Misplaced diaeresis after Armenian digraphs

### ISSUE THREAD

**Issue by dscorbett** [notofonts/armenian#2]
### Font
NotoSansArmenian-Regular.ttf
NotoSerifArmenian-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/9485798f121a42d33b13d03ac0883ea4173c3d95/phaseIII_only/unhinted/ttf/NotoSansArmenian/NotoSansArmenian-Regular.ttf
Site: https://github.com/googlefonts/noto-fonts/blob/9485798f121a42d33b13d03ac0883ea4173c3d95/phaseIII_only/unhinted/otf/NotoSerifArmenian/NotoSerifArmenian-Regular.otf
Date: 2019-11-20

### Font version
Version 2.005

### Issue
After ⟨ՈՒ⟩ and ⟨ու⟩, a diaeresis is placed above the first letter, but it should go above the second letter. (The glyphs for these digraphs cause bugs and seem unnecessary. Why not just use one glyph per letter?)

### Character data
ՈՒ̈ու̈
U+0548 ARMENIAN CAPITAL LETTER VO
U+0552 ARMENIAN CAPITAL LETTER YIWN
U+0308 COMBINING DIAERESIS
U+0578 ARMENIAN SMALL LETTER VO
U+0582 ARMENIAN SMALL LETTER YIWN
U+0308 COMBINING DIAERESIS

### Screenshot
![ՈՒ̈ու̈](https://user-images.githubusercontent.com/1124347/69287664-0cd57500-0bc5-11ea-8a6e-b057c9519a06.png)
![ՈՒ̈ու̈](https://user-images.githubusercontent.com/1124347/69287685-1eb71800-0bc5-11ea-8954-9d9b161ffc6a.png)

**Comment by dscorbett** [comment]
This bug is still present in Noto Sans Armenian 2.008 and Noto Serif Armenian 2.008.

**Comment by simoncozens** [comment]
I tried to fix this by copying the anchors from the individual glyphs onto the digraph. But of course there is no anchor on ւ. To properly fix it, I would have to know whether the dieresis on ւ should appear over the stem or over the centre of the glyph, and I'm pretty sure the answer is "the dieresis does not appear on ւ at all".

**Comment by dscorbett** [comment]
Yes, the diaeresis does not appear on ⟨ւ⟩. It’s okay if the diaeresis isn’t placed properly on that letter, but it shouldn’t be placed so misleadingly on the digraph. A solution would be to remove the anchor points from the ligature glyphs.
